apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: external-dns
      # zur Not Version weglassen, wenn diese nicht existiert
      version: "1.15.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
  provider: google

  # Projekt explizit als Flag (Chart-Versionen lesen 'google.project' teils nicht)
  extraArgs:
    - --google-project=timebertt-dhbw
    - --policy=upsert-only
    - --registry=txt
    - --txt-owner-id=student-sepf
    - --domain-filter=dski23a.timebertt.dev
    - --source=ingress
    - --source=service

  # Secret mounten + ADC-ENV setzen (bruteforce, funktioniert immer)
  google:
    serviceAccountSecret: google-clouddns
    serviceAccountSecretKey: service-account.json
  extraVolumes:
    - name: gcloud
      secret:
        secretName: google-clouddns
  extraVolumeMounts:
    - name: gcloud
      mountPath: /var/secrets/google
      readOnly: true
  extraEnv:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /var/secrets/google/service-account.json

  domainFilters:
    - "dski23a.timebertt.dev"
  txtOwnerId: "student-sepf"
  sources:
    - ingress
    - service
