apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: external-dns
      # version: "1.15.0"    # optional, du kannst die Zeile auch weglassen
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    provider: google

    google:
      project: timebertt-dhbw

    # wichtig: env (nicht extraEnv)
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /var/secrets/google/service-account.json

    extraVolumes:
      - name: gcp-sa
        secret:
          secretName: google-clouddns
    extraVolumeMounts:
      - name: gcp-sa
        mountPath: /var/secrets/google
        readOnly: true

    # optional, aber robust falls 'google.project' ignoriert würde:
    extraArgs:
      - --google-project=timebertt-dhbw

    domainFilters:
      - dski23a.timebertt.dev
    txtOwnerId: student-sepf
    sources:
      - ingress
      - service
