---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1h0m0s
  type: oci
  url: oci://quay.io/jetstack/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      interval: 1h0m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      version: v1.19.1
  install:
    createNamespace: true
  interval: 1h0m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  values:
    crds:
      # Install the cert-manager CustomResourceDefinitions (CRDs), such as Certificate and Issuer.
      # Disabled in default values.
      enabled: true

    global:
      logLevel: 2
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./deploy/cert-manager
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m0s
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age