apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: external-dns
      version: "1.19.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 1m
  values:
    provider:
      name: google

    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /var/secrets/google/credentials.json

    extraVolumes:
      - name: google-credentials
        secret:
          secretName: google-clouddns

    extraVolumeMounts:
      - name: google-credentials
        mountPath: /var/secrets/google
        readOnly: true

    extraArgs:
      google-project: timebertt-dhbw

    sources:
      - ingress
      - service

    registry: txt
    txtOwnerId: "dhbw"

    domainFilters:
      - "dhbw.dski23a.timebertt.dev"

