apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: external-dns
      version: "1.15.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 1m
  values:
    provider: google
    google:
      project: timebertt-dhbw
      serviceAccountSecret: google-clouddns
      serviceAccountSecretKey: credentials.json

    sources:
      - ingress
      - service

    registry: txt
    txtOwnerId: "dhbw"

    domainFilters:
      - "dhbw.dski23a.timebertt.dev"
