apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: ingress-nginx
      version: "4.10.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 1m
  values:
    controller:
      ingressClassResource:
        name: nginx
        default: true
      service:
        type: LoadBalancer
