apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # Im Lab steht, ob Staging oder Prod. Falls nichts anderes da steht, meistens:
    # Staging: https://acme-staging-v02.api.letsencrypt.org/directory
    # Prod:    https://acme-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tom.engels05@icloud.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          cloudDNS:
            project: timebertt-dhbw
            # falls im Lab explizit eine Hosted Zone verlangt wird, käme hier
            # hostedZoneName: example.com.
            serviceAccountSecretRef:
              name: google-clouddns
              key: service-account.json
